spring:
  application:
    name: payprosys-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false

server:
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.payprosys: DEBUG
