spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payprosys
    username: payprosys
    password: payprosys
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    com.payprosys: DEBUG
    org.hibernate.SQL: DEBUG
